### ISSUE TITLE
libglvnd-dev

### ISSUE THREAD

**Issue by soldierofhell** [twobombs/deploy-nvidia-docker#7]
Hi,
Trying to understand how the image is created..

Starting from the beginning, why do you install libglvnd-dev [here](https://github.com/twobombs/deploy-nvidia-docker/blob/c33a54f1eb930f9aa83a3ab74b1d984767fe5b8f/Dockerfile#LL16C251-L16C263), when this library is already installed in cudagl base image (see https://gitlab.com/nvidia/container-images/opengl/blob/ubuntu20.04/glvnd/devel/Dockerfile)

Regards,

**Comment by twobombs** [comment]
You're right: in the 20.04 setting that would be superfluous. However NVidia is moving away from GL images. As the image comes a long way from 14.04, dependancies stay in put as long as they're not conflicting with anything (else) 

As it stands I'll have to (re)make/check GL images made from CUDA (again) but its something we've done before as this repo has been supporting GL before GL container images from NV were a thing. thank you for reaching out.
